version: 1.0.0
config_id: e74cdd7c-03af-453e-bb9d-aa3f5cf2d106
created_at: '2025-11-18T20:00:29.992701Z'
updated_at: '2025-11-18T20:00:29.992701Z'
maintainers:
- name: QA Team
  email: qa@wheelos.cn
  role: Quality Assurance
vehicle_vin: wheelos001
hardware_hash: 1.0.0
wheelos_hash: 1.0.0
description: dkit default configuration
