--flagfile=/apollo/modules/common/data/global_flagfile.txt
--canbus_conf_file=/apollo/modules/canbus/conf/canbus_conf.pb.txt
--enable_chassis_detail_pub
--enable_chassis_detail_sender_pub
--use_control_cmd_check=false
--use_guardian_cmd_check=false
--noreceive_guardian
--estop_brake=10.0
