--flagfile=/apollo/modules/common/data/global_flagfile.txt
--control_conf_file=/apollo/modules/control/conf/control_conf.pb.txt

--enable_csv_debug=false
--use_preview_speed_for_table=false
--steer_angle_rate=100
--enable_gain_scheduler=true
--set_steer_limit=true
--use_vehicle_epb=true

--chassis_pending_queue_size=10
--planning_pending_queue_size=10
--localization_pending_queue_size=10
--pad_msg_pending_queue_size=10

--reverse_heading_control=false
--reverse_heading_vehicle_state=false
--state_transform_to_com_drive=true
--state_transform_to_com_reverse=true
--query_forward_time_point_only=false
--query_forward_station_point_only=false

--max_acceleration_when_stopped=0.01
--max_path_remain_when_stopped=0.1
--minimum_speed_resolution=0.2
--minimum_speed_protection=0.1
--pitch_offset_deg=0.9
--use_throttle_filter=true
--throttle_smoothing_factor=0.08
--use_speed_filter=true
--speed_smoothing_factor=0.1

