version: 1.0.0
config_id: be223ccc-3bff-423b-aec8-072f1470675e
created_at: '2025-11-18T20:00:29.992701Z'
updated_at: '2025-11-18T20:00:29.992701Z'
maintainers:
- name: QA Team
  email: qa@wheelos.cn
  role: Quality Assurance
vehicle_vin: wheelos001
hardware_hash: 1.0.0
wheelos_hash: 1.0.0
description: edu default configuration
